ignores:
  - simple-jwt-auth # self-link for acceptance test
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - husky
  - buffer
  - "@src/*"
  - "@src/.*"
  - rhachet
  - rhachet-brains-anthropic
  - rhachet-brains-xai
  - rhachet-roles-bhrain
  - rhachet-roles-bhuild
  - rhachet-roles-ehmpathy
  - rhachet-roles-rhachet
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@tsconfig/node-lts-strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - tsx
  - tsc-alias
  - yalc
  - "@ehmpathy/error-fns"
  - type-fns
  - "@trivago/prettier-plugin-sort-imports"
  - core-js
  - ts-jest
  - ts-node
