name: test

on:
  workflow_call:
  push:
    branches-ignore:
      - 'main' # exclude main branch, since deploy workflow triggers on main, and calls the test workflow inside of it already
    tags-ignore:
      - v* # exclude tags, since deploy workflow triggers on tags, and calls the test workflow inside of it already

jobs:
  suite:
    uses: ./.github/workflows/.test.yml
